arb-dir: lib/l10n
output-dir: lib/l10n
synthetic-package: false
template-arb-file: flutter_template_en.arb
output-localization-file: flutter_template_localizations.dart
output-class: FlutterTemplateLocalizations

# generate language files with 'flutter gen-l10n'